[package]
name = "nomo-lsp"
version = "0.0.0-20260721120555"
edition = "2024"
license = "MIT"
description = "Language Server Protocol implementation for the Nomo programming language"

[[bin]]
name = "nomo-lsp"
path = "src/main.rs"

[dependencies]
nomo = { git = "https://github.com/nomo-lang/nomo.git", rev = "6acff2bba0113efa3d49254ec2b9c72e1d442b33" }
nomo-lsp-bridge = { git = "https://github.com/nomo-lang/nomo.git", rev = "6acff2bba0113efa3d49254ec2b9c72e1d442b33" }
tower-lsp = "0.20"
tokio = { version = "1", features = ["rt-multi-thread", "io-std", "macros"] }
dashmap = "6"
sha2 = "0.10"
serde_json = "1"
